version: '3.8'
services:
  react-app:
    build: ./react-frontend
    ports:
      - "3000:3000"
  node-app:
    build: ./node-backend
    environment:
      - PGHOST=postgres
      - PGUSER=postgres
      - PGPASSWORD=mysecretpassword
      - PGDATABASE=hello_world_db
    ports:
      - "3001:3001"
    depends_on:
      - postgres
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: coursework
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:

