CREATE TABLE "MOVIE" (
  "ID" INT,
  "POSTER_ID" INT,
  "TITLE" VARCHAR(50),
  "GENRE" VARCHAR(50),
  PRIMARY KEY ("ID")
);

CREATE TABLE "TAGS" (
  "ID" INT,
  "MOVIE_ID" INT,
  "USER_ID" INT,
  "TAG" VARCHAR(50),
  PRIMARY KEY ("ID"),
  CONSTRAINT "FK_TAGS.MOVIE_ID"
    FOREIGN KEY ("MOVIE_ID")
      REFERENCES "MOVIE"("ID")
);

CREATE TABLE "DIRECTOR" (
  "ID" INT,
  "FULL_NAME" VARCHAR(50),
  PRIMARY KEY ("ID")
);

CREATE TABLE "ACTOR" (
  "ID" INT,
  "FULL_NAME" VARCHAR(50),
  PRIMARY KEY ("ID")
);

CREATE TABLE "RATING" (
  "ID" INT,
  "MOVIE_ID" INT,
  "USER_ID" INT,
  PRIMARY KEY ("ID"),
  CONSTRAINT "FK_RATING.MOVIE_ID"
    FOREIGN KEY ("MOVIE_ID")
      REFERENCES "MOVIE"("ID")
);


CREATE TABLE "LINKS" (
  "MOVIE_ID" INT PRIMARY KEY,
  "IMDB_ID" INT NOT NULL UNIQUE,
  "TMDB_ID" INT NOT NULL UNIQUE,
  FOREIGN KEY ("MOVIE_ID") REFERENCES "MOVIE"("ID")
);

CREATE TABLE "POSTER" (
  "IMDB_ID" INT,
  "POSTER" BYTEA,
  FOREIGN KEY ("IMDB_ID") REFERENCES "LINKS"("IMDB_ID")
);

CREATE TABLE "MOVIE_DIRECTOR" (
  "TMDB_ID" INT,
  "DIRECTOR_ID" INT,
  CONSTRAINT "FK_MOVIE_DIRECTOR.DIRECTOR_ID"
    FOREIGN KEY ("DIRECTOR_ID")
      REFERENCES "DIRECTOR"("ID"),
  CONSTRAINT "FK_MOVIE_ACTOR_TMDB_ID"
    FOREIGN KEY ("TMDB_ID") REFERENCES "LINKS"("TMDB_ID")
);

CREATE TABLE "MOVIE_ACTOR" (
  "TMDB_ID" INT,
  "ACTOR_ID" INT,
  CONSTRAINT "FK_MOVIE_ACTOR_TMDB_ID"
    FOREIGN KEY ("TMDB_ID") REFERENCES "LINKS"("TMDB_ID"),
  CONSTRAINT "FK_MOVIE_ACTOR.ACTOR_ID"
    FOREIGN KEY ("ACTOR_ID")
      REFERENCES "ACTOR"("ID")
);

CREATE TABLE "PERSONALITY" (
  "USER_ID" INT,
  "OPENNESS" INT,
  "AGREEABLENESS" INT,
  "EMOTIONAL_STABILITY" INT,
  "CONSCIENTIOUSNESS" INT,
  "EXTRAVERSION" INT,
  PRIMARY KEY ("USER_ID")
);

CREATE TABLE "PERSONALITY_MOVIE" (
  "USER_ID" INT,
  "MOVIE_ID" INT,
  "PREDICTION" INT,
  "ACCURACY" FLOAT,
  CONSTRAINT "FK_PERSONALITY_MOVIE.USER_ID"
    FOREIGN KEY ("USER_ID")
      REFERENCES "PERSONALITY"("USER_ID"),
  CONSTRAINT "FK_PERSONALITY_MOVIE.MOVIE_ID"
    FOREIGN KEY ("MOVIE_ID")
      REFERENCES "MOVIE"("ID")
);


